### PR TITLE
Add/fix build capability for Gaea-C5, Gaea-C6, and container

### LINKED ISSUE #86: gfs_utils fails to build on Gaea-C5 after OS upgrade
### What is wrong?

The EPIC SI team has reinstalled spack-stack-1.6.0 at the same location it existed before. 2 spack-stack module versions will need to be increased to build gfs-utils on Gaea-C5.
In addition, following the ufs-wx-model convention in [PR2448](https://github.com/ufs-community/ufs-weather-model/pull/2448), machine detection and module files have been added for C5 and C6 following PR2448 naming convention, i.e., gaeac5 and gaeac6.

### What should have happened?

Successful build on Gaea-C5 and C6

### What machines are impacted?

All or N/A

### Steps to reproduce

On either Gaea-C5 and C6, standard gfs-utils builds fail.

### Additional information

References NOAA-EMC/global-workflow Issue [#3011](https://github.com/NOAA-EMC/global-workflow/issues/3011)

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
# Description
After the recent Gaea-C5 OS upgrade, gfs_utils fails to build.
This corrects Gaea-C5 build, adds Gaea-C6 build capability (following ufs-wx-model [2448](https://github.com/ufs-community/ufs-weather-model/pull/2448)), and adds containerized build capability.

Refs NOAA-EMC/global-workflow [3011](https://github.com/NOAA-EMC/global-workflow/issues/3011)
Refs NOAA-EMC/global-workflow [3025](https://github.com/NOAA-EMC/global-workflow/issues/3025)
Resolve #86 

# Type of change
- Bug fix (fixes something broken)
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cloned and built on Gaea-C5, Gaea-C6, and container

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

File: ush/module-setup.sh [hunk 1]
```diff
@@ -52,6 +52,13 @@
     fi
     module purge
 
+elif [[ $MACHINE_ID = container ]] ; then
+    # We are in a container
+    if ( ! eval module help > /dev/null 2>&1 ) ; then
+        source /usr/lmod/lmod/init/bash
```
[the remark this answers is not in the document]
Comment (DavidBurrows-NCO) [reply ush/module-setup.sh:58]: @mark-a-potts Is `source /usr/lmod/lmod/init/bash` needed for the container?

[the remark this answers is not in the document]
Comment (mark-a-potts) [reply ush/module-setup.sh:58]: Yes, it is needed if you don't use the /bin/mybash script when you shell in.

File: CMakeLists.txt [hunk 2]
```diff
@@ -25,6 +25,7 @@ endif()
 
 # User options.
 option(OPENMP "use OpenMP threading" ON)
+option(LINK_W3EMC "Link w3emc library" ON)
```
Comment (WalterKolczynski-NOAA) [inline CMakeLists.txt:28]: Not sure the purpose of this new option. Shouldn't this build in the same manner on all platforms? Have the other platforms been tested with this change?

File: modulefiles/gfsutils_generic.lua [hunk 3]
```diff
@@ -0,0 +1,22 @@
+help([[
```
Comment (aerorahul) [inline modulefiles/gfsutils_generic.lua]: What is the purpose of this module file?

File: src/tave.fd/CMakeLists.txt [hunk 4]
```diff
@@ -10,8 +10,13 @@ endif()
 
 set(exe_name tave.x)
 add_executable(${exe_name} ${fortran_src})
-target_link_libraries(${exe_name} PRIVATE bacio::bacio_4
+if(LINK_W3EMC)
```
Comment (aerorahul) [inline src/tave.fd/CMakeLists.txt:13]: Not sure why/where this is causing issues.  CMake should be able to resolve the dependencies.  If there is a version change in bacio that depends on w3emc, it should be coded based on version of bacio.

File: modulefiles/gfsutils_container.intel.lua [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+local stack_intel_ver=os.getenv("stack_intel_ver") or "2021.10.0"
+local stack_impi_ver=os.getenv("stack_impi_ver") or "2021.12.1"
+local cmake_ver=os.getenv("cmake_ver") or "3.27.9"
+
+load(pathJoin("stack-intel", stack_intel_ver))
+load(pathJoin("stack-intel-oneapi-mpi", stack_impi_ver))
+load(pathJoin("cmake", cmake_ver))
+
+load("gfsutils_generic")
```
Comment (aerorahul) [inline modulefiles/gfsutils_container.intel.lua]: Why would the container not load the `gfsutils_common.lua` modulefile?

**Review by aerorahul — CHANGES_REQUESTED** [review]
@DavidBurrows-NCO can you please address some questions from the review?

File: CMakeLists.txt (hunk 2 above)
Comment (mark-a-potts) [reply CMakeLists.txt:28]: This change is required for building with spack-stack-1.8.0. In spack-stack-1.8.0, the skgb function has been added to the g2 library and will throw an error for multiple definitions (it is also in w3emc). Once gfs_utils gets updated to spack-stack-1.8.0 everywhere, the option can be removed.

File: src/tave.fd/CMakeLists.txt (hunk 4 above)
Comment (mark-a-potts) [reply src/tave.fd/CMakeLists.txt:13]: As I mentioned above, this is a problem that is due to changes in the g2 library in spack-stack 1.8.0. In the new g2 library, the skgb function is added to g2 and eliminates the need to link w3emc. If you try to link w3emc as well, you will get an error about multiple definitions.

File: modulefiles/gfsutils_container.intel.lua (hunk 5 above)
Comment (mark-a-potts) [reply modulefiles/gfsutils_container.intel.lua]: The version numbers are not the same in the container, since it is based on spack-stack 1.8.0.

File: modulefiles/gfsutils_generic.lua (hunk 3 above)
Comment (mark-a-potts) [reply modulefiles/gfsutils_generic.lua]: It is a version-less replacement for gfsutils_common.lua that is used when building with a container. We can add in the version numbers, if you want, but leaving them out allows more flexibility to update the container without having to update module files in all repos. I understand that having specific version numbers is desirable for testing and reproducibility, but allowing flexibility in them for the container case improves portability and extensibility.

File: src/tave.fd/CMakeLists.txt (hunk 4 above)
Comment (aerorahul) [reply src/tave.fd/CMakeLists.txt:13]: Understood. Thanks for explaining.
@DavidBurrows-NCO Please create an issue to remove this section when spack-stack is upgraded to 1.8.0 so that we can revisit it then.

File: modulefiles/gfsutils_container.intel.lua (hunk 5 above)
Comment (aerorahul) [reply modulefiles/gfsutils_container.intel.lua]: Understood. Thanks for explaining.
@DavidBurrows-NCO Please create an issue to replace this and consolidate w/ `gfsutils_common.lua` and remove this file when spack-stack is upgraded to 1.8.0 so that we can revisit it then. 
We can accept this for now, but please we cannot afford to maintain multiple copies of modulefiles for different spack-stack versions.  That would be unmanageable for maintenance teams.

File: modulefiles/gfsutils_generic.lua (hunk 3 above)
Comment (aerorahul) [reply modulefiles/gfsutils_generic.lua]: I understand it improves portability and extensibility, but they come at the cost of reproducibility, reliability, and maintainability.  Is there a way to have minimum versions in lua modulefiles?  In cmake one can provide a minimum version.
The `gfsutils_common.lua` provides a mechanism for the user to provide a specific version.  See [here](https://github.com/NOAA-EMC/gfs-utils/blob/develop/modulefiles/gfsutils_common.lua).  If the container has a different version, it can set those version numbers and still be able to leverage `gfsutils_common.lua`.  I think if `default` is provided, it would be similar to this file.

Comment (mark-a-potts) [reply modulefiles/gfsutils_generic.lua]: I'll switch it around so that the container just uses the gfs_common.lua module file along with environment variables to specify the versions available to the container.

Comment (aerorahul) [reply modulefiles/gfsutils_generic.lua]: sounds good.  Thanks @mark-a-potts

File: modulefiles/gfsutils_gaeac5.intel.lua [hunk 6]
```diff
@@ -3,15 +3,15 @@ help([[
   on the NOAA RDHPC machine Gaea C5 using Intel-2023.1.0.
 ]])
 
-whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea ]===])
+whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea C5]===])
```
Comment (aerorahul) [inline modulefiles/gfsutils_gaeac5.intel.lua]:
```suggestion
whatis([===[Loads libraries needed for building the GFS utilities Gaea C5]===])
```

File: modulefiles/gfsutils_gaeac6.intel.lua [hunk 7]
```diff
@@ -0,0 +1,32 @@
+help([[
+  This module loads libraries required for building and running GFS UTILS 
+  on the NOAA RDHPC machine Gaea C6 using Intel-2023.1.0.
+]])
+
+whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea C6 ]===])
```
Comment (aerorahul) [inline modulefiles/gfsutils_gaeac6.intel.lua]:
```suggestion
whatis([===[Loads libraries needed for building the GFS utilities on Gaea C6 ]===])
```

File: src/tave.fd/CMakeLists.txt (hunk 4 above)
Comment (DavidBurrows-NCO) [reply src/tave.fd/CMakeLists.txt:13]: @aerorahul @mark-a-potts Issue #88 created

File: modulefiles/gfsutils_container.intel.lua (hunk 5 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_container.intel.lua]: @aerorahul @mark-a-potts Issue #88 created

File: modulefiles/gfsutils_gaeac6.intel.lua [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/gsi-addon/install/modulefiles/Core")
+
+stack_intel_ver=os.getenv("stack_intel_ver") or "2023.2.0"
+load(pathJoin("stack-intel", stack_intel_ver))
+
+stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.29"
+load(pathJoin("stack-cray-mpich", stack_cray_mpich_ver))
+
+stack_python_ver=os.getenv("stack_python_ver") or "3.11.6"
+load(pathJoin("stack-python", stack_python_ver))
```
Comment (aerorahul) [inline modulefiles/gfsutils_gaeac6.intel.lua]: What is using python in this repo?

File: modulefiles/gfsutils_gaeac6.intel.lua [hunk 9]
```diff
@@ -0,0 +1,32 @@
+help([[
+  This module loads libraries required for building and running GFS UTILS 
+  on the NOAA RDHPC machine Gaea C6 using Intel-2023.1.0.
+]])
+
+whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea C6 ]===])
+
+prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/unified-env/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/gsi-addon/install/modulefiles/Core")
```
Comment (aerorahul) [inline modulefiles/gfsutils_gaeac6.intel.lua]: please remove the duplicate line

File: modulefiles/gfsutils_gaeac5.intel.lua [hunk 10]
```diff
@@ -3,15 +3,15 @@ help([[
...
 
-stack_intel_ver=os.getenv("stack_intel_ver") or "2023.1.0"
+stack_intel_ver=os.getenv("stack_intel_ver") or "2023.2.0"
 load(pathJoin("stack-intel", stack_intel_ver))
 
-stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.25"
+stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.28"
 load(pathJoin("stack-cray-mpich", stack_cray_mpich_ver))
 
 stack_python_ver=os.getenv("stack_python_ver") or "3.11.6"
```
Comment (aerorahul) [inline modulefiles/gfsutils_gaeac5.intel.lua]: What is using python in this repo?

File: modulefiles/gfsutils_gaeac6.intel.lua (hunk 9 above)
Comment (aerorahul) [reply modulefiles/gfsutils_gaeac6.intel.lua]: I notice its not duplicate.  Why are both unified-env and gsi-addon envs needed to be loaded.

Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac6.intel.lua]: @aerorahul unified-env has bufr/12.0.1, and gsi-addon has bufr/11.7.0 needed by gfs-utils. Initially when I ported to C5, I had to have both MODULEPATHs. I just tested C5 with only gsi-addon, and the build was successful. I haven't had access to C6 today so will test that build when I can.

File: modulefiles/gfsutils_gaeac5.intel.lua (hunk 10 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac5.intel.lua]: @aerorahul I have removed the python load and retested the C5 build successfully.  I haven't had access to C6 today so will test that build when I can.

File: modulefiles/gfsutils_container.intel.lua (hunk 5 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_container.intel.lua]: @aerorahul Container is now using gfsutils_common. Thanks @mark-a-potts

File: modulefiles/gfsutils_gaeac5.intel.lua (hunk 6 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac5.intel.lua]: @aerorahul I shouldn't miss these. Thank you.

File: modulefiles/gfsutils_gaeac6.intel.lua (hunk 7 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac6.intel.lua]: @aerorahul I shouldn't miss these. Thank you.

File: modulefiles/gfsutils_gaeac6.intel.lua (hunk 8 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac6.intel.lua]: @aerorahul I removed the python load and retested the C6 build successfully.

File: CMakeLists.txt (hunk 2 above)
Comment (DavidBurrows-NCO) [reply CMakeLists.txt:28]: @WalterKolczynski-NOAA @aerorahul Should I create a ticket to remove this when spack-stack is upgraded as well?

Comment (WalterKolczynski-NOAA) [reply CMakeLists.txt:28]: Yes please

Comment (DavidBurrows-NCO) [reply CMakeLists.txt:28]: @WalterKolczynski-NOAA Added to #88 and updated the issue ticket.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

File: modulefiles/gfsutils_gaeac6.intel.lua (hunk 9 above)
Comment (DavidBurrows-NCO) [reply modulefiles/gfsutils_gaeac6.intel.lua]: gfs-utils has been tested on both C5 and C6.

**Review by aerorahul — APPROVED** [review]
looks good. not sure what shellnorms is complaining about.

**Comment by DavidBurrows-NCO** [comment]
Thanks, Rahul. I looked through a few times and don't see anything strange.
